name: Generate

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3'

      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: '1.2.2'

      - name: Install dependencies
        run: |
          poetry install

      - name: Run generate.py
        run: |
          poetry run python generate.py